# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SealCli < Formula
  desc "CLI for the Seal Subscriptions Merchant API"
  homepage "https://github.com/hieutapt/seals-subscription-cli"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hieutapt/seals-subscription-cli/releases/download/v0.3.2/seal-cli_0.3.2_darwin_amd64.tar.gz"
      sha256 "920d6e333887311952e73395ae75ac1eba4897fffb2550d8378125dd34c075ef"

      define_method(:install) do
        bin.install "seal-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hieutapt/seals-subscription-cli/releases/download/v0.3.2/seal-cli_0.3.2_darwin_arm64.tar.gz"
      sha256 "681edc35ca1bc19c0ab3030321b63a8abf177ca96f0b825fa60d7906356e5f54"

      define_method(:install) do
        bin.install "seal-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hieutapt/seals-subscription-cli/releases/download/v0.3.2/seal-cli_0.3.2_linux_amd64.tar.gz"
      sha256 "4e6475a704701b7d9c78d46f015bf0c9849699f35ea81c945c7f070cde711fcb"
      define_method(:install) do
        bin.install "seal-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hieutapt/seals-subscription-cli/releases/download/v0.3.2/seal-cli_0.3.2_linux_arm64.tar.gz"
      sha256 "e147f8bd4f1a9d7d038a0abca4774654996fc153e12c49ba3fa3d8e8afcb2516"
      define_method(:install) do
        bin.install "seal-cli"
      end
    end
  end

  test do
    system "#{bin}/seal-cli", "--help"
  end
end
