# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SealCli < Formula
  desc "CLI for the Seal Subscriptions Merchant API"
  homepage "https://github.com/hieutapt/seals-subscription-cli"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hieutapt/seals-subscription-cli/releases/download/v0.3.1/seal-cli_0.3.1_darwin_amd64.tar.gz"
      sha256 "c05444740eb7cd0b8f59fadbc7e5b7207ec70801cb1ba0eef3e052617950b53e"

      define_method(:install) do
        bin.install "seal-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hieutapt/seals-subscription-cli/releases/download/v0.3.1/seal-cli_0.3.1_darwin_arm64.tar.gz"
      sha256 "d5bf783690535ddfb310d7821c8987592a6e43613896cf1580440a51b3921225"

      define_method(:install) do
        bin.install "seal-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hieutapt/seals-subscription-cli/releases/download/v0.3.1/seal-cli_0.3.1_linux_amd64.tar.gz"
      sha256 "425cb66d76a4dc60893c0ac63dc2b660ba562705d22193cded775a91144457d6"
      define_method(:install) do
        bin.install "seal-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hieutapt/seals-subscription-cli/releases/download/v0.3.1/seal-cli_0.3.1_linux_arm64.tar.gz"
      sha256 "4bf39097f357de20880c2921434185f3784d635481d6255c929b9b63e084f49c"
      define_method(:install) do
        bin.install "seal-cli"
      end
    end
  end

  test do
    system "#{bin}/seal-cli", "--help"
  end
end
