# This file is auto-generated by GoReleaser. Do not edit manually.
# It will be updated automatically when a new release is tagged.
class SealCli < Formula
  desc "CLI for the Seal Subscriptions Merchant API"
  homepage "https://github.com/hieu/seals-subscription-cli"
  version "0.0.0-placeholder"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/hieu/seals-subscription-cli/releases/download/v0.0.0/seal-cli_0.0.0_darwin_arm64.tar.gz"
      sha256 "placeholder"
    end
    on_intel do
      url "https://github.com/hieu/seals-subscription-cli/releases/download/v0.0.0/seal-cli_0.0.0_darwin_amd64.tar.gz"
      sha256 "placeholder"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hieu/seals-subscription-cli/releases/download/v0.0.0/seal-cli_0.0.0_linux_arm64.tar.gz"
      sha256 "placeholder"
    end
    on_intel do
      url "https://github.com/hieu/seals-subscription-cli/releases/download/v0.0.0/seal-cli_0.0.0_linux_amd64.tar.gz"
      sha256 "placeholder"
    end
  end

  def install
    bin.install "seal-cli"
  end

  test do
    system "#{bin}/seal-cli", "--help"
  end
end
